import { useState, useRef, useCallback, useEffect } from 'react';
import { Client } from '@gradio/client';
import {
  Upload, Camera, Video, X, Loader2, CheckCircle2,
  AlertTriangle, Info, Leaf, Calendar,
  Weight, Clock, ChevronDown, ChevronUp, RefreshCw,
  Download, FlaskConical, Sparkles, ScanLine
} from 'lucide-react';
import { getDiseaseInfo, getSeverityColor } from '../data/diseaseData';

const TABS = [
  { id: 'upload', label: 'Upload Image', icon: Upload },
  { id: 'capture', label: 'Capture Photo', icon: Camera },
  { id: 'live', label: 'Live Detection', icon: Video },
];

async function callHuggingFaceAPI(file) {
  const client = await Client.connect('Naveen2916/plantdisease');
  const result = await client.predict('/predict', { image: file });
  // result.data[0] is a flat array of {label, confidence} objects sorted by confidence desc
  const rawList = Array.isArray(result.data[0]) ? result.data[0] : result.data;
  if (!rawList || rawList.length === 0) throw new Error('No result received from model. Please try again.');
  return {
    label: rawList[0].label,
    confidences: rawList.map((item) => ({ label: item.label, confidence: item.confidence })),
  };
}

function LoaderDots() {
  return (
    <div className="flex items-center justify-center gap-2 py-8">
      {[0, 1, 2].map((i) => (
        <div
          key={i}
          className="w-3 h-3 bg-green-400 rounded-full"
          style={{ animation: `loadDot 1.4s ease-in-out ${i * 0.16}s infinite both` }}
        />
      ))}
    </div>
  );
}

function ConfidenceBar({ value, label, isTop }) {
  const [width, setWidth] = useState(0);
  useEffect(() => {
    const t = setTimeout(() => setWidth(value), 100);
    return () => clearTimeout(t);
  }, [value]);

  return (
    <div className="space-y-1">
      <div className="flex justify-between text-xs">
        <span className={isTop ? 'text-green-300 font-medium' : 'text-green-100/60'}>{label}</span>
        <span className={isTop ? 'text-green-400 font-bold' : 'text-green-100/50'}>{(value * 100).toFixed(1)}%</span>
      </div>
      <div className="h-2 bg-white/5 rounded-full overflow-hidden">
        <div
          className={`h-full rounded-full transition-all duration-1000 ease-out ${isTop ? 'bg-gradient-to-r from-green-500 to-lime-400' : 'bg-green-800'}`}
          style={{ width: `${width * 100}%` }}
        />
      </div>
    </div>
  );
}

function DiseaseResult({ result, imageUrl }) {
  const [expandTreatment, setExpandTreatment] = useState(true);
  const [expandUsage, setExpandUsage] = useState(false);
  const info = getDiseaseInfo(result?.label);
  const severityClass = getSeverityColor(info.severity);

  const handleDownload = () => {
    const content = `PLANT DISEASE ANALYSIS REPORT
${'='.repeat(50)}
Date: ${new Date().toLocaleDateString()}
Plant: ${info.plant}
Disease: ${info.name}
Severity: ${info.severity}
Confidence: ${result?.confidences ? (result.confidences[0]?.confidence * 100).toFixed(1) : 'N/A'}%

DESCRIPTION:
${info.description}

CAUSES:
${info.causes.map((c, i) => `${i + 1}. ${c}`).join('\n')}

TREATMENT:
${info.treatment.map((t, i) => `${i + 1}. ${t}`).join('\n')}

FERTILIZER/PRODUCT: ${info.fertilizer}

USAGE:
- Quantity: ${info.usage.quantity}
- Frequency: ${info.usage.frequency}
- Best Time: ${info.usage.bestTime}

Generated by PlantAI Disease Classifier
`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `plant-disease-report-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-4 animate-fade-up">
      {/* Header card */}
      <div className="glass rounded-2xl p-5 border border-green-500/20">
        <div className="flex items-start gap-4">
          {imageUrl && (
            <img
              src={imageUrl}
              alt="Analyzed plant"
              className="w-20 h-20 rounded-xl object-cover border border-white/10 flex-shrink-0"
            />
          )}
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 mb-1 flex-wrap">
              <span className="text-2xl">{info.icon}</span>
              <h3 className="text-white font-bold text-xl">{info.name}</h3>
              <span className={`px-2.5 py-0.5 rounded-full text-xs font-semibold border ${severityClass}`}>
                {info.severity === 'None' ? '✓ Healthy' : `⚠ ${info.severity}`}
              </span>
            </div>
            <p className="text-green-400/80 text-sm font-medium mb-2">{info.plant}</p>
            {result?.confidences && (
              <div className="space-y-1.5 mt-3">
                {result.confidences.slice(0, 3).map((c, i) => (
                  <ConfidenceBar
                    key={i}
                    value={c.confidence}
                    label={c.label.replace(/_/g, ' ').replace(/___/g, ' — ')}
                    isTop={i === 0}
                  />
                ))}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Description */}
      <div className="glass rounded-2xl p-5 border border-white/5">
        <div className="flex items-center gap-2 mb-3">
          <Info className="w-4 h-4 text-green-400" />
          <h4 className="text-white font-semibold">Disease Description</h4>
        </div>
        <p className="text-green-100/70 text-sm leading-relaxed">{info.description}</p>
      </div>

      {/* Causes */}
      <div className="glass rounded-2xl p-5 border border-white/5">
        <div className="flex items-center gap-2 mb-3">
          <AlertTriangle className="w-4 h-4 text-yellow-400" />
          <h4 className="text-white font-semibold">Causes</h4>
        </div>
        <ul className="space-y-2">
          {info.causes.map((cause, i) => (
            <li key={i} className="flex items-start gap-2 text-sm text-green-100/70">
              <span className="text-yellow-400/60 mt-0.5 flex-shrink-0">▸</span>
              {cause}
            </li>
          ))}
        </ul>
      </div>

      {/* Treatment */}
      <div className="glass rounded-2xl border border-white/5 overflow-hidden">
        <button
          className="w-full flex items-center justify-between p-5 hover:bg-white/5 transition-colors"
          onClick={() => setExpandTreatment(!expandTreatment)}
        >
          <div className="flex items-center gap-2">
            <Leaf className="w-4 h-4 text-green-400" />
            <h4 className="text-white font-semibold">Treatment & Fertilizer</h4>
          </div>
          {expandTreatment ? <ChevronUp className="w-4 h-4 text-green-400" /> : <ChevronDown className="w-4 h-4 text-green-400" />}
        </button>
        {expandTreatment && (
          <div className="px-5 pb-5 space-y-4 border-t border-white/5">
            <div className="mt-4 p-3 rounded-xl bg-green-500/10 border border-green-500/20">
              <div className="flex items-center gap-2 mb-1">
                <FlaskConical className="w-4 h-4 text-green-400" />
                <span className="text-green-300 text-sm font-semibold">Recommended Product</span>
              </div>
              <p className="text-white text-sm">{info.fertilizer}</p>
            </div>
            <ul className="space-y-2">
              {info.treatment.map((step, i) => (
                <li key={i} className="flex items-start gap-2.5 text-sm text-green-100/70">
                  <span className="w-5 h-5 rounded-full bg-green-500/20 border border-green-500/30 text-green-400 text-xs flex items-center justify-center flex-shrink-0 mt-0.5 font-bold">
                    {i + 1}
                  </span>
                  {step}
                </li>
              ))}
            </ul>
          </div>
        )}
      </div>

      {/* Usage */}
      <div className="glass rounded-2xl border border-white/5 overflow-hidden">
        <button
          className="w-full flex items-center justify-between p-5 hover:bg-white/5 transition-colors"
          onClick={() => setExpandUsage(!expandUsage)}
        >
          <div className="flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-blue-400" />
            <h4 className="text-white font-semibold">How to Use Fertilizer</h4>
          </div>
          {expandUsage ? <ChevronUp className="w-4 h-4 text-blue-400" /> : <ChevronDown className="w-4 h-4 text-blue-400" />}
        </button>
        {expandUsage && (
          <div className="px-5 pb-5 border-t border-white/5">
            <div className="mt-4 grid grid-cols-1 sm:grid-cols-3 gap-3">
              <div className="p-3 rounded-xl bg-blue-500/10 border border-blue-500/20">
                <div className="flex items-center gap-1.5 mb-1.5">
                  <Weight className="w-3.5 h-3.5 text-blue-400" />
                  <span className="text-blue-300 text-xs font-semibold uppercase tracking-wide">Quantity</span>
                </div>
                <p className="text-white text-xs leading-relaxed">{info.usage.quantity}</p>
              </div>
              <div className="p-3 rounded-xl bg-purple-500/10 border border-purple-500/20">
                <div className="flex items-center gap-1.5 mb-1.5">
                  <Clock className="w-3.5 h-3.5 text-purple-400" />
                  <span className="text-purple-300 text-xs font-semibold uppercase tracking-wide">Frequency</span>
                </div>
                <p className="text-white text-xs leading-relaxed">{info.usage.frequency}</p>
              </div>
              <div className="p-3 rounded-xl bg-teal-500/10 border border-teal-500/20">
                <div className="flex items-center gap-1.5 mb-1.5">
                  <Calendar className="w-3.5 h-3.5 text-teal-400" />
                  <span className="text-teal-300 text-xs font-semibold uppercase tracking-wide">Best Time</span>
                </div>
                <p className="text-white text-xs leading-relaxed">{info.usage.bestTime}</p>
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Actions */}
      <div className="flex gap-3">
        <button
          onClick={handleDownload}
          className="flex-1 flex items-center justify-center gap-2 py-3 glass border border-white/10 hover:border-green-500/30 text-white text-sm font-medium rounded-xl transition-all hover:bg-white/5"
        >
          <Download className="w-4 h-4" />
          Download Report
        </button>
      </div>
    </div>
  );
}

export default function Classify() {
  const [activeTab, setActiveTab] = useState('upload');
  const [imageFile, setImageFile] = useState(null);
  const [imageUrl, setImageUrl] = useState('');
  const [isDragging, setIsDragging] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState('');
  const [cameraActive, setCameraActive] = useState(false);
  const [liveActive, setLiveActive] = useState(false);
  const [liveResult, setLiveResult] = useState(null);
  const [liveLoading, setLiveLoading] = useState(false);
  const [history, setHistory] = useState([]);

  const fileInputRef = useRef(null);
  const videoRef = useRef(null);
  const canvasRef = useRef(null);
  const streamRef = useRef(null);
  const liveIntervalRef = useRef(null);

  const stopCamera = useCallback(() => {
    if (streamRef.current) {
      streamRef.current.getTracks().forEach((t) => t.stop());
      streamRef.current = null;
    }
    if (liveIntervalRef.current) {
      clearInterval(liveIntervalRef.current);
      liveIntervalRef.current = null;
    }
    setCameraActive(false);
    setLiveActive(false);
  }, []);

  useEffect(() => () => stopCamera(), [stopCamera]);

  useEffect(() => {
    if (activeTab !== 'capture' && activeTab !== 'live') stopCamera();
  }, [activeTab, stopCamera]);

  const startCamera = useCallback(async () => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: 'environment' }, audio: false });
      streamRef.current = stream;
      if (videoRef.current) {
        videoRef.current.srcObject = stream;
        videoRef.current.play();
      }
      setCameraActive(true);
      setError('');
    } catch {
      setError('Camera access denied. Please allow camera permission in your browser settings.');
    }
  }, []);

  const predict = useCallback(async (file, url) => {
    setIsLoading(true);
    setResult(null);
    setError('');
    try {
      const data = await callHuggingFaceAPI(file);
      const resultData = { label: data.label, confidences: data.confidences };
      setResult(resultData);
      setHistory((prev) => [
        { id: Date.now(), imageUrl: url, result: resultData, timestamp: new Date().toLocaleTimeString() },
        ...prev.slice(0, 4),
      ]);
    } catch (err) {
      if (err.name === 'AbortError') {
        setError('Request timed out. The model may be loading — please try again in a moment.');
      } else if (err.message.includes('503') || err.message.includes('502')) {
        setError('Model is waking up. Hugging Face Spaces take 30–60 seconds to start. Please try again shortly.');
      } else {
        setError(`Analysis failed: ${err.message}`);
      }
    } finally {
      setIsLoading(false);
    }
  }, []);

  const handleFileSelect = useCallback((file) => {
    if (!file || !file.type.startsWith('image/')) {
      setError('Please select a valid image file (JPG, PNG, WebP).');
      return;
    }
    const url = URL.createObjectURL(file);
    setImageFile(file);
    setImageUrl(url);
    setResult(null);
    setError('');
  }, []);

  const handleDrop = useCallback((e) => {
    e.preventDefault();
    setIsDragging(false);
    const file = e.dataTransfer.files[0];
    if (file) handleFileSelect(file);
  }, [handleFileSelect]);

  const capturePhoto = useCallback(() => {
    const video = videoRef.current;
    const canvas = canvasRef.current;
    if (!video || !canvas) return;
    canvas.width = video.videoWidth;
    canvas.height = video.videoHeight;
    canvas.getContext('2d').drawImage(video, 0, 0);
    canvas.toBlob((blob) => {
      const file = new File([blob], 'capture.jpg', { type: 'image/jpeg' });
      const url = URL.createObjectURL(blob);
      setImageFile(file);
      setImageUrl(url);
      setResult(null);
      setError('');
      stopCamera();
      setActiveTab('upload');
    }, 'image/jpeg', 0.9);
  }, [stopCamera]);

  const startLiveDetection = useCallback(async () => {
    await startCamera();
    setLiveActive(true);
    setLiveResult(null);
  }, [startCamera]);

  const captureLiveFrame = useCallback(async () => {
    const video = videoRef.current;
    const canvas = canvasRef.current;
    if (!video || !canvas || liveLoading) return;
    canvas.width = video.videoWidth;
    canvas.height = video.videoHeight;
    canvas.getContext('2d').drawImage(video, 0, 0);
    canvas.toBlob(async (blob) => {
      setLiveLoading(true);
      const file = new File([blob], 'live.jpg', { type: 'image/jpeg' });
      try {
        const data = await callHuggingFaceAPI(file);
        if (data) setLiveResult({ label: data.label, confidences: data.confidences });
      } catch {
        // silent fail for live frames
      } finally {
        setLiveLoading(false);
      }
    }, 'image/jpeg', 0.8);
  }, [liveLoading]);

  return (
    <div className="min-h-screen pt-20 pb-16 px-4 sm:px-6">
      <canvas ref={canvasRef} className="hidden" />
      <div className="max-w-6xl mx-auto">
        {/* Header */}
        <div className="text-center mb-10">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full glass border border-green-500/30 text-green-400 text-sm font-medium mb-5">
            <ScanLine className="w-4 h-4" />
            AI Disease Classifier
          </div>
          <h1 className="text-3xl sm:text-4xl font-bold text-white mb-3">
            Analyze Your <span className="text-green-400">Plant</span>
          </h1>
          <p className="text-green-100/60 max-w-xl mx-auto">
            Upload a clear photo of your plant leaf to detect diseases and get expert treatment advice.
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Left — Input Panel */}
          <div className="space-y-4">
            {/* Tabs */}
            <div className="glass rounded-2xl p-1.5 flex gap-1">
              {TABS.map(({ id, label, icon: Icon }) => (
                <button
                  key={id}
                  onClick={() => setActiveTab(id)}
                  className={`flex-1 flex items-center justify-center gap-1.5 py-2.5 px-3 rounded-xl text-xs sm:text-sm font-medium transition-all duration-200 ${
                    activeTab === id
                      ? 'bg-green-500 text-black shadow-lg shadow-green-500/20'
                      : 'text-green-100/60 hover:text-white hover:bg-white/5'
                  }`}
                >
                  <Icon className="w-4 h-4" />
                  <span className="hidden sm:inline">{label}</span>
                  <span className="sm:hidden">{label.split(' ')[0]}</span>
                </button>
              ))}
            </div>

            {/* Upload Tab */}
            {activeTab === 'upload' && (
              <div className="space-y-4">
                <div
                  className={`relative glass rounded-2xl border-2 border-dashed transition-all duration-200 ${
                    isDragging
                      ? 'border-green-400 bg-green-400/5'
                      : imageUrl
                      ? 'border-green-500/30'
                      : 'border-white/10 hover:border-green-500/30'
                  }`}
                  onDragOver={(e) => { e.preventDefault(); setIsDragging(true); }}
                  onDragLeave={() => setIsDragging(false)}
                  onDrop={handleDrop}
                >
                  {imageUrl ? (
                    <div className="relative">
                      <img src={imageUrl} alt="Preview" className="w-full h-72 object-cover rounded-2xl" />
                      <button
                        onClick={() => { setImageUrl(''); setImageFile(null); setResult(null); setError(''); }}
                        className="absolute top-3 right-3 w-8 h-8 rounded-full bg-black/60 border border-white/20 flex items-center justify-center text-white hover:bg-red-500/80 transition-colors"
                      >
                        <X className="w-4 h-4" />
                      </button>
                      {result && (
                        <div className="absolute bottom-3 left-3">
                          <span className="px-2.5 py-1 rounded-full bg-green-500 text-black text-xs font-bold flex items-center gap-1">
                            <CheckCircle2 className="w-3 h-3" /> Analyzed
                          </span>
                        </div>
                      )}
                    </div>
                  ) : (
                    <div
                      className="flex flex-col items-center justify-center py-16 cursor-pointer"
                      onClick={() => fileInputRef.current?.click()}
                    >
                      <div className="w-16 h-16 rounded-2xl bg-green-500/10 border border-green-500/20 flex items-center justify-center mb-4 animate-bounce-gentle">
                        <Upload className="w-7 h-7 text-green-400" />
                      </div>
                      <p className="text-white font-medium mb-1">Drop image here or click to browse</p>
                      <p className="text-green-100/40 text-sm">JPG, PNG, WebP — max 10MB</p>
                    </div>
                  )}
                  <input
                    ref={fileInputRef}
                    type="file"
                    accept="image/*"
                    className="hidden"
                    onChange={(e) => e.target.files[0] && handleFileSelect(e.target.files[0])}
                  />
                </div>

                {imageFile && !result && (
                  <button
                    onClick={() => predict(imageFile, imageUrl)}
                    disabled={isLoading}
                    className="btn-shine w-full py-4 bg-green-500 hover:bg-green-400 disabled:opacity-60 text-black font-bold text-base rounded-2xl transition-all duration-200 flex items-center justify-center gap-2 glow-green"
                  >
                    {isLoading ? (
                      <><Loader2 className="w-5 h-5 animate-spin" /> Analyzing Plant…</>
                    ) : (
                      <><Sparkles className="w-5 h-5" /> Analyze Disease</>
                    )}
                  </button>
                )}
                {result && (
                  <button
                    onClick={() => { setImageUrl(''); setImageFile(null); setResult(null); setError(''); }}
                    className="w-full py-3 glass border border-white/10 hover:border-green-500/30 text-white font-medium text-sm rounded-2xl transition-all flex items-center justify-center gap-2"
                  >
                    <RefreshCw className="w-4 h-4" /> Analyze Another Plant
                  </button>
                )}
              </div>
            )}

            {/* Capture Tab */}
            {activeTab === 'capture' && (
              <div className="space-y-4">
                <div className="relative glass rounded-2xl overflow-hidden border border-white/10">
                  {cameraActive ? (
                    <>
                      <video ref={videoRef} autoPlay playsInline muted className="w-full h-72 object-cover" />
                      {/* Scan overlay */}
                      <div className="absolute inset-0 pointer-events-none">
                        <div className="absolute inset-8 border-2 border-green-400/40 rounded-2xl">
                          <div className="absolute top-0 left-0 w-8 h-8 border-t-2 border-l-2 border-green-400 rounded-tl-xl" />
                          <div className="absolute top-0 right-0 w-8 h-8 border-t-2 border-r-2 border-green-400 rounded-tr-xl" />
                          <div className="absolute bottom-0 left-0 w-8 h-8 border-b-2 border-l-2 border-green-400 rounded-bl-xl" />
                          <div className="absolute bottom-0 right-0 w-8 h-8 border-b-2 border-r-2 border-green-400 rounded-br-xl" />
                        </div>
                        <div
                          className="absolute left-8 right-8 h-0.5 bg-gradient-to-r from-transparent via-green-400 to-transparent opacity-70"
                          style={{ animation: 'scanLine 2s ease-in-out infinite', top: '40%' }}
                        />
                      </div>
                    </>
                  ) : (
                    <div className="flex flex-col items-center justify-center h-72">
                      <Camera className="w-12 h-12 text-green-400/40 mb-3" />
                      <p className="text-green-100/50 text-sm">Camera preview will appear here</p>
                    </div>
                  )}
                </div>

                <div className="flex gap-3">
                  {!cameraActive ? (
                    <button
                      onClick={startCamera}
                      className="flex-1 py-3.5 bg-green-500 hover:bg-green-400 text-black font-bold rounded-2xl transition-all flex items-center justify-center gap-2"
                    >
                      <Camera className="w-5 h-5" /> Open Camera
                    </button>
                  ) : (
                    <>
                      <button
                        onClick={capturePhoto}
                        className="flex-1 py-3.5 bg-green-500 hover:bg-green-400 text-black font-bold rounded-2xl transition-all flex items-center justify-center gap-2"
                      >
                        <Camera className="w-5 h-5" /> Capture & Analyze
                      </button>
                      <button
                        onClick={stopCamera}
                        className="py-3.5 px-4 glass border border-red-500/30 text-red-400 hover:bg-red-500/10 rounded-2xl transition-all"
                      >
                        <X className="w-5 h-5" />
                      </button>
                    </>
                  )}
                </div>
              </div>
            )}

            {/* Live Tab */}
            {activeTab === 'live' && (
              <div className="space-y-4">
                <div className="relative glass rounded-2xl overflow-hidden border border-white/10">
                  {(liveActive || cameraActive) ? (
                    <>
                      <video ref={videoRef} autoPlay playsInline muted className="w-full h-72 object-cover" />
                      {/* Live overlay */}
                      <div className="absolute top-3 left-3 flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-red-500/80 text-white text-xs font-bold">
                        <span className="w-2 h-2 rounded-full bg-white animate-pulse" /> LIVE
                      </div>
                      {liveResult && (
                        <div className="absolute bottom-0 left-0 right-0 p-3 bg-gradient-to-t from-black/90 to-transparent">
                          <p className="text-white font-semibold text-sm">
                            {liveResult.label?.replace(/_/g, ' ').replace(/___/g, ' — ')}
                          </p>
                          {liveResult.confidences?.[0] && (
                            <p className="text-green-400 text-xs">
                              {(liveResult.confidences[0].confidence * 100).toFixed(1)}% confidence
                            </p>
                          )}
                        </div>
                      )}
                    </>
                  ) : (
                    <div className="flex flex-col items-center justify-center h-72">
                      <Video className="w-12 h-12 text-green-400/40 mb-3" />
                      <p className="text-green-100/50 text-sm">Live detection stream will appear here</p>
                    </div>
                  )}
                </div>

                {liveLoading && (
                  <div className="text-center text-green-400/70 text-sm flex items-center justify-center gap-2">
                    <Loader2 className="w-4 h-4 animate-spin" /> Analyzing frame...
                  </div>
                )}

                <div className="flex gap-3">
                  {!liveActive ? (
                    <button
                      onClick={startLiveDetection}
                      className="flex-1 py-3.5 bg-green-500 hover:bg-green-400 text-black font-bold rounded-2xl transition-all flex items-center justify-center gap-2"
                    >
                      <Video className="w-5 h-5" /> Start Live Detection
                    </button>
                  ) : (
                    <>
                      <button
                        onClick={captureLiveFrame}
                        disabled={liveLoading}
                        className="flex-1 py-3.5 bg-green-500 hover:bg-green-400 disabled:opacity-60 text-black font-bold rounded-2xl transition-all flex items-center justify-center gap-2"
                      >
                        {liveLoading ? <Loader2 className="w-5 h-5 animate-spin" /> : <ScanLine className="w-5 h-5" />}
                        {liveLoading ? 'Analyzing...' : 'Capture & Analyze Frame'}
                      </button>
                      <button
                        onClick={stopCamera}
                        className="py-3.5 px-4 glass border border-red-500/30 text-red-400 hover:bg-red-500/10 rounded-2xl transition-all"
                      >
                        <X className="w-5 h-5" />
                      </button>
                    </>
                  )}
                </div>
              </div>
            )}

            {/* Error */}
            {error && (
              <div className="flex items-start gap-3 p-4 rounded-xl bg-red-500/10 border border-red-500/30 text-red-400 text-sm">
                <AlertTriangle className="w-5 h-5 flex-shrink-0 mt-0.5" />
                <span>{error}</span>
              </div>
            )}

            {/* Tips */}
            <div className="glass rounded-2xl p-4 border border-white/5">
              <p className="text-green-400 text-xs font-semibold mb-2 uppercase tracking-wide">📌 Tips for Best Results</p>
              <ul className="space-y-1.5 text-green-100/60 text-xs">
                <li>• Use clear, well-lit images of affected leaves</li>
                <li>• Capture only the leaf — avoid soil or background clutter</li>
                <li>• Zoom in on the diseased area for better accuracy</li>
                <li>• JPG or PNG formats work best</li>
              </ul>
            </div>
          </div>

          {/* Right — Results Panel */}
          <div className="space-y-4">
            {isLoading && (
              <div className="glass rounded-2xl p-8 text-center border border-green-500/20">
                <div className="w-16 h-16 mx-auto mb-4 rounded-full border-4 border-green-500/30 border-t-green-400 animate-spin" />
                <h3 className="text-white font-semibold mb-2">Analyzing Your Plant</h3>
                <p className="text-green-100/60 text-sm">Our AI is examining the image for disease patterns…</p>
                <LoaderDots />
                <p className="text-green-100/40 text-xs">This may take 15–30 seconds on first run</p>
              </div>
            )}

            {!isLoading && result && (
              <DiseaseResult result={result} imageUrl={imageUrl} />
            )}

            {!isLoading && !result && !error && (
              <div className="glass rounded-2xl p-10 text-center border border-white/5">
                <div className="w-20 h-20 mx-auto mb-4 rounded-2xl bg-green-500/10 border border-green-500/20 flex items-center justify-center text-4xl animate-float">
                  🌿
                </div>
                <h3 className="text-white font-semibold text-lg mb-2">Ready to Analyze</h3>
                <p className="text-green-100/50 text-sm">Upload or capture a plant image to get started with AI disease detection.</p>
              </div>
            )}

            {/* History */}
            {history.length > 0 && (
              <div className="glass rounded-2xl p-4 border border-white/5">
                <p className="text-white font-semibold text-sm mb-3 flex items-center gap-2">
                  <Clock className="w-4 h-4 text-green-400" /> Recent Analyses
                </p>
                <div className="space-y-2">
                  {history.map((h) => {
                    const info = getDiseaseInfo(h.result?.label);
                    return (
                      <div key={h.id} className="flex items-center gap-3 p-2.5 rounded-xl hover:bg-white/5 transition-colors cursor-pointer"
                        onClick={() => { setResult(h.result); setImageUrl(h.imageUrl); setActiveTab('upload'); }}>
                        <img src={h.imageUrl} alt="history" className="w-10 h-10 rounded-lg object-cover border border-white/10 flex-shrink-0" />
                        <div className="flex-1 min-w-0">
                          <p className="text-white text-xs font-medium truncate">{info.name}</p>
                          <p className="text-green-100/40 text-xs">{h.timestamp}</p>
                        </div>
                        <span className="text-green-400/60 text-xs">{info.icon}</span>
                      </div>
                    );
                  })}
                </div>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Scan line keyframe */}
      <style>{`
        @keyframes scanLine {
          0%, 100% { top: 20%; }
          50% { top: 75%; }
        }
      `}</style>
    </div>
  );
}
